# Generated by Django 5.2.1 on 2025-05-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='categoria',
            field=models.CharField(choices=[('pecho', 'Pecho'), ('espalda', 'Espalda'), ('hombros', 'Hombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('piernas', 'Piernas'), ('abdominales', 'Abdominales'), ('cardio', 'Cardio'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AddField(
            model_name='rutina',
            name='categoria',
            field=models.CharField(choices=[('pecho', 'Pecho'), ('espalda', 'Espalda'), ('hombros', 'Hombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('piernas', 'Piernas'), ('abdominales', 'Abdominales'), ('cardio', 'Cardio'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
