# Generated by Django 5.2.1 on 2025-05-31 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0002_ejercicio_categoria_rutina_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejercicio',
            options={'ordering': ['rutina', 'nombre']},
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='categoria',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='rutina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='entrenamiento.rutina'),
        ),
    ]
