# Generated by Django 5.2.1 on 2025-05-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0003_alter_ejercicio_options_remove_ejercicio_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción y técnica del ejercicio', null=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen de referencia del ejercicio', null=True, upload_to='ejercicios/'),
        ),
    ]
